# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 21:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the company', max_length=100, verbose_name='name')),
                ('address_line1', models.CharField(blank=True, max_length=100, verbose_name='Address 1')),
                ('address_line2', models.CharField(blank=True, max_length=100, verbose_name='Address 2')),
                ('phone_number', models.CharField(blank=True, max_length=70)),
                ('homepage', models.TextField(validators=[django.core.validators.URLValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar', models.ImageField(upload_to='/images/')),
                ('phone_number', models.CharField(blank=True, max_length=70)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='contacts.Company')),
            ],
        ),
    ]
