# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 03:09
from __future__ import unicode_literals

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('last_name',), 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=contacts.models.get_image_path),
        ),
    ]
